{{- if .Values.config.persistentVolume.enabled -}}
{{- if not .Values.config.persistentVolume.existingClaim -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "terraria.fullname" . }}-config
  {{- include "terraria.namespace" . | nindent 2 }}
  labels:
    {{- include "terraria.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.config.persistentVolume.accessModes | nindent 4 }}
  {{- if .Values.config.persistentVolume.volumeBindingMode }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.config.persistentVolume.size }}
{{- end }}
{{- end }}
