apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "terraria.fullname" . }}-nginx-config
  {{- include "terraria.namespace" . | nindent 2 }}
  labels:
    {{- include "terraria.labels" . | nindent 4 }}
data:
  nginx.conf: |
    worker_processes  3;
    error_log  /dev/stdout;
    events {
      worker_connections  10240;
    }
    http {
      access_log	/dev/stdout;
      server {
          listen       8080;
          server_name  _;
          location / {
              root   html;
              index  index.html index.htm;
          }
          location ~* \.(png)$ {
            expires -1;
          }
      }
    }

