{{- if .Values.flyingsnake.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "terraria.fullname" . }}-flyingsnake
  {{- include "terraria.namespace" . | nindent 2 }}
  labels:
    {{- include "terraria.labels" . | nindent 4 }}
spec:
  type: {{ .Values.rest.service.type }}
  {{- with .Values.flyingsnake.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}

  {{- end }}
  ports:
    - port: 8080
      targetPort: flyingsnake
      name: flyingsnake
      protocol: TCP
      {{- with .Values.flyingsnake.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
  selector:
    {{- include "terraria.selectorLabels" . | nindent 4 }}
{{- end }}
