{{- if and .Values.ingress.enabled ( or .Values.flyingsnake.enabled .Values.rest.enabled ) -}}
{{- $fullName := include "terraria.fullname" . -}}
{{- $pathtype := .Values.ingress.pathtype -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels: {{ include "terraria.labels" . | nindent 4 }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
        {{- if $.Values.flyingsnake.enabled }}
          - path: /
            pathType: {{ $pathtype }}
            backend:
              service:
                name: {{ $fullName }}-flyingsnake
                port:
                  name: flyingsnake
        {{- end }}
        {{- if $.Values.rest.enabled }}
          - path: /rest
            pathType: {{ $pathtype }}
            backend:
              service:
                name: {{ $fullName }}-rest
                port:
                  name: rest
        {{- end }}
  {{- end }}
{{- end}}
