# Default values for Terraria

# Name override
nameOverride: ""

# Full name override
fullnameOverride: ""

# Server
server:

  # Service settings
  # Ref: https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-intro/
  service:

    # The service type
    type: ClusterIP

    # The service port
    port: 7777

    # The port the server will be exposed as externally, if the service type is "NodePort", this
    # will be the fixed port instead of a random one in the node port range
    nodePort: null

    # Load balancer IP, if service type is "LoadBalancer"
    loadBalancerIP: null

  # The name of the server
  name: "{{ .Release.Name }}"

  # If debug messages should be logged
  debugLoggingEnabled: false

  # Language of the server:
  #  - English = en-US
  #  - German = de-DE
  #  - Italian = it-IT
  #  - French = fr-FR
  #  - Spanish = es-ES
  #  - Russian = ru-RU
  #  - Chinese = zh-Hans
  #  - Portuguese = pt-BR
  #  - Polish = pl-PL
  language: en-US

  # Maximum number of allowed players
  maxPlayers:
    # Default number of max players, for non-reserved player slots
    base: 8

    # Number of reserved player slots past the default that can be joined by reserved players
    #  tshock-only
    reserved: 20

  # The maximum number of connections per IP, or no limit if null
  maxConnectionsPerIP: null

  # Password of the server
  password: null

  # Forces the server to keep updating, and not hibernating when no players are on. This results
  # in time passing, grass growing, etc.
  forceUpdates: false

  # The restart policy applied to the server pod
  restartPolicy: Always

# Additional protection against cheats
antiCheatProtection:

  # If additional cheat protection is enabled
  enabled: true

  # If range checks based on distance between players and their block placements are enabled
  #  tshock-only
  rangeChecks: true

# Prevents non-hardcore players from connecting
#  tshock-only
hardcoreOnly: false

# Prevents softcore players from connecting
#  tshock-only
mediumcoreOnly: false

# Spawn protection
#  tshock-only
spawnProtection:

  # If tiles are protected around the spawn tile
  enabled: true

  # Tile radius around the spawn tile
  radius: 10

# Hardmode
#  tshock-only
hardmode:

  # If hardmode can be triggered by the Wall of Flesh or the /starthardmode command
  triggerable: true

  # Allows the crimson to spread when a world is in hardmode
  spreadCrimson: true

  # Allows the corruption to spread when a world is in hardmode
  spreadCorruption: true

  # Allows the hallow to spread when a world is in hardmode
  spreadHallow: true

announcementBox:

  # If the text announcements the Announcement Box makes when pulsed from wire are enabled
  enabled: true

  # The announcement box text messaging range in pixels, null for server-wide announcements
  range: null

world:

  # World name, used for the world save file
  name: "{{ .Release.Name }}"

  # World size: small, medium, large
  size: small

  # World difficulty: classic, expert, master or journey
  difficulty: classic

  # Seed used to generate the world, null to use a random seed
  seed: null

  # Reduces maximum liquids moving at the same time. If enabled may reduce lags but liquids may
  # take longer to settle
  slowLiquids: false

  # If auto save is enabled
  #  tshock-only, cannot be disabled for the vanilla image
  autoSave: true

  # If saving should be announced
  #  tshock-only
  announceSave: true

  # Whether to save the world if the server crashes from an unhandled exception
  #  tshock-only
  saveOnCrash: true

  # Whether to save the world when the last player disconnects
  #  tshock-only
  saveOnLastPlayerExit: true

  # World backup, backups are stored next to the world file under a backup directory
  #  tshock-only
  backup:

    # If saving caused by backing up should be announced
    announceSave: true

    # Backup interval, setting the interval to zero disables backups
    interval: 0m

    # How long backups should be kept
    keepFor: 1h

  # Rollbacks to keep
  rollbacksToKeep: 2

  # Persistent volume where the worlds are stored
  persistentVolume:
    # If a persistent volume should be used to store worlds, otherwise uses emptyDir
    enabled: true

    # The persistent volume access modes
    # Must match those of existing PV or dynamic provisioner
    # Ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
    accessModes:
      - ReadWriteOnce

    # An existing persistent volume claim name, will be used instead of the default one
    # If defined, the persistent volume claim must be created manually before volume will be bound
    existingClaim: null

    # The size of the persistent volume
    size: 2Gi

    # The volume binding mode
    # If undefined, the default mode will be used.
    volumeBindingMode: null

  # Worlds empty dir
  emptyDir:
    # Volume size limit
    sizeLimit: null

# Plugins
#  tshock-only
plugins:

  # Whether the API version should be checked, disabling this allows older plugins to run
  versionCheck: true

# Config
config:
  # Persistent volume where tshock configs are stored
  persistentVolume:
    # If a persistent volume should be used to store worlds, otherwise uses emptyDir
    enabled: true

    # The persistent volume access modes
    # Must match those of existing PV or dynamic provisioner
    # Ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
    accessModes:
      - ReadWriteOnce

    # An existing persistent volume claim name, will be used instead of the default one
    # If defined, the persistent volume claim must be created manually before volume will be bound
    existingClaim: null

    # The size of the persistent volume
    size: 10Mi

  # Worlds empty dir
  emptyDir:
    # Volume size limit
    sizeLimit: null

# Chat
#  tshock-only
chat:

  # Specifies which string starts a command. Note: Will not function properly if the string length
  # is longer than one character.
  commandSpecifier: "/"

  # Specifies which string starts a command silently. Note: Will not function properly if the string
  # length is longer than one character.
  silentCommandSpecifier: "."

  # Whether to announce a player's geographic location on join, based on their IP.
  announceGeographicLocation: false

  # Whether a player's IP should be displayed to users with the log permission.
  displayPlayerIPOnJoin: false

  # The color of the broadcast messages
  broadcastColor: "#7fffd4"

  # Chat format
  #  placeholders:
  #   - ${groupName}
  #   - ${groupPrefix}
  #   - ${playerName}
  #   - ${groupSuffix}
  #   - ${message}
  format: "${groupPrefix}${playerName}${groupSuffix}: ${message}"

  # Chat bubbles above players' heads
  bubbles:

    # If chat bubbles are enabled
    enabled: true

  # Super admin settings
  superAdmin:

    # The chat color for the super admin group. Color can be RGB as an array or HEX color value.
    color: "#ffffff"

    # The super admin prefix
    prefix: "(Super Admin) "

    # The super admin suffix
    suffix: ""

# Rest Service
#  tshock-only
rest:

  # If the rest service is enabled, is ignored if not tshock
  enabled: false

  # If rest connections should be logged
  loggingEnabled: false

  # The maximum REST requests in the bucket before denying requests, minimum value is 5
  maxRequestsPerInterval: 5

  # How often in minutes the REST requests bucket is decreased by one, minimum value is 1 minute
  requestBucketDecreaseIntervalMinutes: 1

  # Access tokens that are persistent between restarts
  # Ref: https://tshock.readme.io/reference/rest-api-endpoints
  applicationTokens:
    # - name: rest-ban-token
    #   user: rest-banner
    #   userGroup: rest-ban-groupo

  # Service settings
  # Ref: https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-intro/
  service:

    # The service type
    type: ClusterIP

    # The service port
    port: 7878

    # The port the rest api will be exposed as externally, if the service type is "NodePort", this
    # will be the fixed port instead of a random one in the node port range
    nodePort: null

    # Load balancer IP, if service type is "LoadBalancer"
    loadBalancerIP: null

image:

  # The pull policy that is used for all images, unless overridden for a specific image
  pullPolicy: IfNotPresent

  # The pull secrets
  pullSecrets: []

  # The terraria server image
  terraria:
    # The image type: tshock, vanilla, null to derive from image tag
    type: null
    repository: registry.fnemeth.net/terraria/tshock
    tag: tshock-latest
    # The pull policy, image.pullPolicy is used if not set
    pullPolicy: null

  # The tools image
  tools:
    repository: cybermaxke/tools
    tag: alpine-3.14.2
    # The pull policy, image.pullPolicy is used if not set
    pullPolicy: null

# Configuration when used in combination with terre
terre:

  # Configuration related to terre auto discovery
  autoDiscovery:

    # If auto discovery is enabled
    enabled: true

    # Allows players to automatically join this server when they connect to the terre, without
    # having to explicitly teleport
    allowAutoJoin: true

    # The label that terre will use to automatically detect the terraria server
    selectorLabel:
      name: terraria-server
      value: true

# Extra init containers that are added to the deployment
extraInitContainers: {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious choice
  # for the user. This also increases chances charts run on environments with little resources,
  # such as Minikube. If you do want to specify resources, uncomment the following lines, adjust
  # them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 1
  #   memory: 1Gi
  # requests:
  #   cpu: 100m
  #   memory: 512Mi

# Startup probe configuration
startupProbe:
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 6
  successThreshold: 1

# Liveness probe configuration
livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 1
  successThreshold: 1

# Readiness probe configuration
readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 1
  successThreshold: 1

nodeSelector: {}

# Node tolerations for scheduling to nodes with taints
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
tolerations: []

affinity: {}

rbac:
  # Specifies whether RBAC resources should be created
  create: true

# Service account
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
